### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by knrt10** [p-society/typeracer-cli#11]
Please suggest any changes in logo.

**Comment by palash25** [comment]
Whatever you like. Lets keep this issue open till tonight and then make the final decision.

**Comment by knrt10** [comment]
Nah not intrigued. What if they are like me and not typing ninjas

**Comment by palash25** [comment]
"Practice for noobs contests for ninja"
"So you think you can touch-type?"

choose whatever you like

**Comment by knrt10** [comment]
@palash25 word limit should be max 3

**Comment by knrt10** [comment]
@IamRaviTejaG any comments?

**Comment by IamRaviTejaG** [comment]
How about "Don't type typo"?

**Comment by palash25** [comment]
Love it @IamRaviTejaG

**Comment by knrt10** [comment]
I am finally going with **Don't type typo"** cool? cc @palash25 @IamRaviTejaG

**Comment by IamRaviTejaG** [comment]
Yup. 😄

**Comment by palash25** [comment]
Love it :heart:

**Comment by IamRaviTejaG** [comment]
@palash25 Blushes! 😝

**Comment by palash25** [comment]
@IamRaviTejaG can you add the logo file to the artwork repo. I'm kinda busy right now.

Also if you get the time can you make a behance and dribble profile for the p-soc and dump all the logos and posters over there. If you do this all mention this on the #outreach channel on slack and the online presence issue https://github.com/p-society/goals/issues/19 so that everyone knows about it.

**Comment by IamRaviTejaG** [comment]
Gimme an hour to get all of it done. :)

**Comment by IamRaviTejaG** [comment]
@palash25 Once I'm done with the logo, I'll upload it to the artwork repo. Behance is getting me a certificate error, so I can't visit it, will try tomorrow. And dribbble, I'm using twitter login. Okay?!

**Comment by palash25** [comment]
All fine with me.
